name: weakness_work
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^5.0.0
  intl: ^0.17.0
  carousel_slider: ^4.0.0
  html: ^0.15.0
  flutter_material_symbols: ^0.0.1
  material_design_icons_flutter: ^5.0.6996
  cupertino_icons: ^1.0.3
  file_picker: ^4.2.0
  video_player: ^2.2.7
  chewie: ^1.2.2
  path_provider: ^2.0.9
  path: ^1.8.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Klee One
      fonts:
        - asset: fonts/KleeOne-Regular.ttf

  uses-material-design: true

  assets:
    - images/