name: weakness_work
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.8
  speech_to_text: ^6.1.1
  provider: ^6.0.5
  intl: 0.18.0
  carousel_slider: ^4.0.0
  html: ^0.15.0
  flutter_material_symbols: ^0.0.1
  material_design_icons_flutter: ^6.0.7096
  cupertino_icons: ^1.0.3
  file_picker: ^5.2.10
  video_player: ^2.2.7
  chewie: ^1.2.2
  path_provider: ^2.0.9
  path: ^1.8.2
  permission_handler: ^10.2.0
  google_speech: ^2.2.0
  flutter_sound_lite: ^8.5.0
  rxdart: ^0.27.3
  file: ^6.0.0
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  firebase_ui_auth: ^1.4.3

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "images/appicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "images/appicon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

flutter:
  fonts:
    - family: Klee One
      fonts:
        - asset: fonts/KleeOne-Regular.ttf

  uses-material-design: true

  assets:
    - assets/test_service_account.json
    - images/


dependency_overrides:
  file: ^6.0.0