name: weakness_work
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_material_symbols: ^0.0.1
  material_design_icons_flutter: ^5.0.6996
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/